// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v2k/beam/Emittance.proto
// Protobuf C++ Version: 6.33.4

#ifndef v2k_2fbeam_2fEmittance_2eproto_2epb_2eh
#define v2k_2fbeam_2fEmittance_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_v2k_2fbeam_2fEmittance_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_v2k_2fbeam_2fEmittance_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_v2k_2fbeam_2fEmittance_2eproto;
}  // extern "C"
namespace v2k {
namespace beam {
class Emittance;
struct EmittanceDefaultTypeInternal;
extern EmittanceDefaultTypeInternal _Emittance_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Emittance_class_data_;
}  // namespace beam
}  // namespace v2k
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace v2k {
namespace beam {

// ===================================================================


// -------------------------------------------------------------------

class Emittance final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:v2k.beam.Emittance) */ {
 public:
  inline Emittance() : Emittance(nullptr) {}
  ~Emittance() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Emittance* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Emittance));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Emittance(::google::protobuf::internal::ConstantInitialized);

  inline Emittance(const Emittance& from) : Emittance(nullptr, from) {}
  inline Emittance(Emittance&& from) noexcept
      : Emittance(nullptr, ::std::move(from)) {}
  inline Emittance& operator=(const Emittance& from) {
    CopyFrom(from);
    return *this;
  }
  inline Emittance& operator=(Emittance&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Emittance& default_instance() {
    return *reinterpret_cast<const Emittance*>(
        &_Emittance_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Emittance& a, Emittance& b) { a.Swap(&b); }
  inline void Swap(Emittance* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Emittance* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Emittance* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Emittance>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Emittance& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Emittance& from) { Emittance::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Emittance* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "v2k.beam.Emittance"; }

  explicit Emittance(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Emittance(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Emittance& from);
  Emittance(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Emittance&& from) noexcept
      : Emittance(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimeFieldNumber = 1,
    kCurrentFieldNumber = 2,
    kEmittanceFieldNumber = 3,
  };
  // int64 time = 1;
  void clear_time() ;
  ::int64_t time() const;
  void set_time(::int64_t value);

  private:
  ::int64_t _internal_time() const;
  void _internal_set_time(::int64_t value);

  public:
  // double current = 2;
  void clear_current() ;
  double current() const;
  void set_current(double value);

  private:
  double _internal_current() const;
  void _internal_set_current(double value);

  public:
  // double emittance = 3;
  void clear_emittance() ;
  double emittance() const;
  void set_emittance(double value);

  private:
  double _internal_emittance() const;
  void _internal_set_emittance(double value);

  public:
  // @@protoc_insertion_point(class_scope:v2k.beam.Emittance)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Emittance& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t time_;
    double current_;
    double emittance_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_v2k_2fbeam_2fEmittance_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Emittance_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Emittance

// int64 time = 1;
inline void Emittance::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t Emittance::time() const {
  // @@protoc_insertion_point(field_get:v2k.beam.Emittance.time)
  return _internal_time();
}
inline void Emittance::set_time(::int64_t value) {
  _internal_set_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:v2k.beam.Emittance.time)
}
inline ::int64_t Emittance::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_;
}
inline void Emittance::_internal_set_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = value;
}

// double current = 2;
inline void Emittance::clear_current() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double Emittance::current() const {
  // @@protoc_insertion_point(field_get:v2k.beam.Emittance.current)
  return _internal_current();
}
inline void Emittance::set_current(double value) {
  _internal_set_current(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:v2k.beam.Emittance.current)
}
inline double Emittance::_internal_current() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_;
}
inline void Emittance::_internal_set_current(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_ = value;
}

// double emittance = 3;
inline void Emittance::clear_emittance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.emittance_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double Emittance::emittance() const {
  // @@protoc_insertion_point(field_get:v2k.beam.Emittance.emittance)
  return _internal_emittance();
}
inline void Emittance::set_emittance(double value) {
  _internal_set_emittance(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:v2k.beam.Emittance.emittance)
}
inline double Emittance::_internal_emittance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.emittance_;
}
inline void Emittance::_internal_set_emittance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.emittance_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace beam
}  // namespace v2k


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // v2k_2fbeam_2fEmittance_2eproto_2epb_2eh
