version: "3"

vars:
  DOCKER_REGISTRY: ghcr.io/blabtm
  SCHEMA_DIR: "{{.ROOT_DIR}}/schema"
  CONFIG_DIR: "{{.ROOT_DIR}}/config"
  TOOLS_DIR: "{{.ROOT_DIR}}/tools"

dotenv:
  - platform/env/secret.env
  - platform/env/build.local.env
  - platform/env/build.env

includes:
  platform:
    taskfile: ./platform/Taskfile.yaml
    dir: ./platform
  native:
    taskfile: ./native/Taskfile.yaml
    dir: ./native
  jvm:
    taskfile: ./jvm/Taskfile.yaml
    dir: ./jvm
  py:
    taskfile: ./py/Taskfile.yaml
    dir: ./py

tasks:
  rpk:profile:create:
    cmds:
      - |
        rpk profile create v2k                                  \
          --set brokers=$RP_HOST:$RP_LAN_PORT                   \
          --set schema_registry.addresses=$RP_HOST:$RP_SR_PORT

  schema:install:
    cmds:
      - "{{.TOOLS_DIR}}/sync/schema-install.sh"

