networks:
  v2k:
    external: true

services:
  sol.mf:
    image: ghcr.io/blabtm/sol.mf:latest
    environment:
      CONFIG_DIR: /etc/config
      BLOB_DIR: /etc/blob
    volumes:
      - $CONFIG_DIR:/etc/config
      - $BLOB_DIR:/etc/blob
    networks:
      - v2k
