// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v2k/beam/EnergySpread.proto
// Protobuf Java Version: 4.33.5

package org.blab.v2k;

@com.google.protobuf.Generated
public final class EnergySpreadOuterClass extends com.google.protobuf.GeneratedFile {
  private EnergySpreadOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 5,
      /* suffix= */ "",
      "EnergySpreadOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnergySpreadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v2k.beam.EnergySpread)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <code>double current = 2;</code>
     * @return The current.
     */
    double getCurrent();

    /**
     * <code>double energy_spread = 3;</code>
     * @return The energySpread.
     */
    double getEnergySpread();
  }
  /**
   * Protobuf type {@code v2k.beam.EnergySpread}
   */
  public static final class EnergySpread extends
      com.google.protobuf.GeneratedMessage implements
      org.blab.v2k.io.Record,
      // @@protoc_insertion_point(message_implements:v2k.beam.EnergySpread)
      EnergySpreadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 5,
        /* suffix= */ "",
        "EnergySpread");
    }
    // Use EnergySpread.newBuilder() to construct.
    private EnergySpread(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EnergySpread() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.blab.v2k.EnergySpreadOuterClass.internal_static_v2k_beam_EnergySpread_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.blab.v2k.EnergySpreadOuterClass.internal_static_v2k_beam_EnergySpread_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.blab.v2k.EnergySpreadOuterClass.EnergySpread.class, org.blab.v2k.EnergySpreadOuterClass.EnergySpread.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_ = 0L;
    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }

    public static final int CURRENT_FIELD_NUMBER = 2;
    private double current_ = 0D;
    /**
     * <code>double current = 2;</code>
     * @return The current.
     */
    @java.lang.Override
    public double getCurrent() {
      return current_;
    }

    public static final int ENERGY_SPREAD_FIELD_NUMBER = 3;
    private double energySpread_ = 0D;
    /**
     * <code>double energy_spread = 3;</code>
     * @return The energySpread.
     */
    @java.lang.Override
    public double getEnergySpread() {
      return energySpread_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
      if (java.lang.Double.doubleToRawLongBits(current_) != 0) {
        output.writeDouble(2, current_);
      }
      if (java.lang.Double.doubleToRawLongBits(energySpread_) != 0) {
        output.writeDouble(3, energySpread_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (java.lang.Double.doubleToRawLongBits(current_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, current_);
      }
      if (java.lang.Double.doubleToRawLongBits(energySpread_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, energySpread_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.blab.v2k.EnergySpreadOuterClass.EnergySpread)) {
        return super.equals(obj);
      }
      org.blab.v2k.EnergySpreadOuterClass.EnergySpread other = (org.blab.v2k.EnergySpreadOuterClass.EnergySpread) obj;

      if (getTime()
          != other.getTime()) return false;
      if (java.lang.Double.doubleToLongBits(getCurrent())
          != java.lang.Double.doubleToLongBits(
              other.getCurrent())) return false;
      if (java.lang.Double.doubleToLongBits(getEnergySpread())
          != java.lang.Double.doubleToLongBits(
              other.getEnergySpread())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + CURRENT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCurrent()));
      hash = (37 * hash) + ENERGY_SPREAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getEnergySpread()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.blab.v2k.EnergySpreadOuterClass.EnergySpread prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v2k.beam.EnergySpread}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v2k.beam.EnergySpread)
        org.blab.v2k.EnergySpreadOuterClass.EnergySpreadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.blab.v2k.EnergySpreadOuterClass.internal_static_v2k_beam_EnergySpread_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.blab.v2k.EnergySpreadOuterClass.internal_static_v2k_beam_EnergySpread_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.blab.v2k.EnergySpreadOuterClass.EnergySpread.class, org.blab.v2k.EnergySpreadOuterClass.EnergySpread.Builder.class);
      }

      // Construct using org.blab.v2k.EnergySpreadOuterClass.EnergySpread.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        time_ = 0L;
        current_ = 0D;
        energySpread_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.blab.v2k.EnergySpreadOuterClass.internal_static_v2k_beam_EnergySpread_descriptor;
      }

      @java.lang.Override
      public org.blab.v2k.EnergySpreadOuterClass.EnergySpread getDefaultInstanceForType() {
        return org.blab.v2k.EnergySpreadOuterClass.EnergySpread.getDefaultInstance();
      }

      @java.lang.Override
      public org.blab.v2k.EnergySpreadOuterClass.EnergySpread build() {
        org.blab.v2k.EnergySpreadOuterClass.EnergySpread result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.blab.v2k.EnergySpreadOuterClass.EnergySpread buildPartial() {
        org.blab.v2k.EnergySpreadOuterClass.EnergySpread result = new org.blab.v2k.EnergySpreadOuterClass.EnergySpread(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.blab.v2k.EnergySpreadOuterClass.EnergySpread result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.time_ = time_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.current_ = current_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.energySpread_ = energySpread_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.blab.v2k.EnergySpreadOuterClass.EnergySpread) {
          return mergeFrom((org.blab.v2k.EnergySpreadOuterClass.EnergySpread)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.blab.v2k.EnergySpreadOuterClass.EnergySpread other) {
        if (other == org.blab.v2k.EnergySpreadOuterClass.EnergySpread.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getCurrent()) != 0) {
          setCurrent(other.getCurrent());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getEnergySpread()) != 0) {
          setEnergySpread(other.getEnergySpread());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                time_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                current_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                energySpread_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long time_ ;
      /**
       * <code>int64 time = 1;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {

        time_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }

      private double current_ ;
      /**
       * <code>double current = 2;</code>
       * @return The current.
       */
      @java.lang.Override
      public double getCurrent() {
        return current_;
      }
      /**
       * <code>double current = 2;</code>
       * @param value The current to set.
       * @return This builder for chaining.
       */
      public Builder setCurrent(double value) {

        current_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double current = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        current_ = 0D;
        onChanged();
        return this;
      }

      private double energySpread_ ;
      /**
       * <code>double energy_spread = 3;</code>
       * @return The energySpread.
       */
      @java.lang.Override
      public double getEnergySpread() {
        return energySpread_;
      }
      /**
       * <code>double energy_spread = 3;</code>
       * @param value The energySpread to set.
       * @return This builder for chaining.
       */
      public Builder setEnergySpread(double value) {

        energySpread_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double energy_spread = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnergySpread() {
        bitField0_ = (bitField0_ & ~0x00000004);
        energySpread_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:v2k.beam.EnergySpread)
    }

    // @@protoc_insertion_point(class_scope:v2k.beam.EnergySpread)
    private static final org.blab.v2k.EnergySpreadOuterClass.EnergySpread DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.blab.v2k.EnergySpreadOuterClass.EnergySpread();
    }

    public static org.blab.v2k.EnergySpreadOuterClass.EnergySpread getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnergySpread>
        PARSER = new com.google.protobuf.AbstractParser<EnergySpread>() {
      @java.lang.Override
      public EnergySpread parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EnergySpread> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnergySpread> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.blab.v2k.EnergySpreadOuterClass.EnergySpread getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2k_beam_EnergySpread_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_v2k_beam_EnergySpread_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033v2k/beam/EnergySpread.proto\022\010v2k.beam\"" +
      "D\n\014EnergySpread\022\014\n\004time\030\001 \001(\003\022\017\n\007current" +
      "\030\002 \001(\001\022\025\n\renergy_spread\030\003 \001(\001B\016\n\014org.bla" +
      "b.v2kb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_v2k_beam_EnergySpread_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_v2k_beam_EnergySpread_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_v2k_beam_EnergySpread_descriptor,
        new java.lang.String[] { "Time", "Current", "EnergySpread", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
