pluginManagement {
    repositories {
        maven {
            url = uri("http://192.168.0.37:8081/nexus/content/repositories/gradle-plugins/")
            allowInsecureProtocol = true
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            url = uri("http://192.168.0.37:8081/nexus/content/repositories/confluent/")
            allowInsecureProtocol = true
        }
        mavenCentral()
    }
}

rootProject.name = "v2k"

def projects = [
        "share:io",
        "share:math",
        "em-es",
]

projects.each { path ->
    def dir = new File(settingsDir, path.replaceAll(":", "/"))

    if (dir.exists()) {
        include(path)
    } else {
        println("Skipping missing project: ${path}")
    }
}
