networks:
  v2k:
    external: true

volumes:
  grafana:

services:
  grafana:
    image: ghcr.io/blabtm/v2k.grafana:latest
    ports:
      - target: 3000
        published: $GRAFANA_PORT
        mode: ingress
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hamedkarbasi93-kafka-datasource
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - v2k
