networks:
  v2k:
    external: true

services:
  sm:
    image: ghcr.io/blabtm/v2k.sm:latest
    ports:
      - target: 80
        published: $SM_PORT
        mode: ingress
    environment:
      CONFIG_PATH: /etc/v2k/config
      DEPLOY_PATH: /etc/v2k/deploy
    volumes:
      - $REPO_PATH/config:/etc/v2k/config
      - $REPO_PATH/.deploy:/etc/v2k/deploy
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - v2k
