version: "3"

tasks:
  setup:
    status:
      - test -n "$(docker ps --filter 'status=running' | grep paper-latex-1)"
    cmds:
      - docker compose up -d
    internal: true

  clean:
    cmds:
      - rm -f *.aux *.bcf *.log *.toc *.xml _minted

  build:
    deps: [setup]
    cmds:
      - docker exec -it paper-latex-1 lualatex thesis.tex
      - docker exec -it paper-latex-1 biber thesis
      - docker exec -it paper-latex-1 lualatex thesis.tex
