version: "3"

includes:
  paper:
    taskfile: ./paper/Taskfile.yaml
    dir: ./paper

tasks:
  setup:
    status:
      - test -n "$(ls . | grep node_modules)"
    cmds:
      - npm install
  build:
    deps: [setup]
    cmds:
      - npm run build
