networks:
  v2k:
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=hamedkarbasi93-kafka-datasource
    volumes:
      - ./grafana-kafka-datasource/dist:/var/lib/grafana/plugins/hamedkarbasi93-kafka-datasource
    networks:
      - v2k