version: '3'

includes:
  grafana-kafka-datasource: 
    taskfile: ./grafana-kafka-datasource/Taskfile.yaml
    dir: ./grafana-kafka-datasource

tasks:
  image:
    desc: build grafana's image
    deps:
      - grafana-kafka-datasource:build
    cmds:
      - docker build -t {{.DOCKER_REGISTRY}}/v2k.grafana:latest .
