version: "3"

includes:
  ui:
    taskfile: ./ui/Taskfile.yaml
    dir: ./ui

tasks:
  build:amd64:
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    cmds:
      - go build -o sm_amd64 .
    generates:
      - sm_amd64

  build:arm64:
    env:
      GOOS: linux
      GOARCH: arm64
      CGO_ENABLED: 0
    cmds:
      - go build -o sm_arm64 .
    generates:
      - sm_arm64

  release:
    cmds:
      - task: build:amd64
      - task: build:arm64
      - envsubst '${TAG}' < util/install.sh > install.sh

  image:
    cmds:
      - docker build -t {{.DOCKER_REGISTRY}}/v2k.sm:latest .

  publish:
    cmds:
      - docker push {{.DOCKER_REGISTRY}}/v2k.sm:latest

  run:
    env:
      ADDR: ":8080"
      MODULE_PATH: "{{.ROOT_DIR}}"
      CONFIG_PATH: "{{.CONFIG_DIR}}"
      DEPLOY_PATH: "{{.DEPLOY_DIR}}"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
    cmds:
      - go run ./rest

