version: "3"

vars:
  VERSION: 0.0.1

env:
  VERSION: "{{.VERSION}}"

tasks:
  build:amd64:
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    cmds:
      - go build -o sm_{{.VERSION}}_amd64 .
    generates:
      - sm_{{.VERSION}}_amd64

  build:amd64:deb:
    cmds:
      - mkdir -p sm_{{.VERSION}}_amd64
      - mkdir -p sm_{{.VERSION}}_amd64/usr/local/bin
      - mkdir -p sm_{{.VERSION}}_amd64/etc/sm
      - mkdir -p sm_{{.VERSION}}_amd64/DEBIAN
      - go build -o sm_{{.VERSION}}_amd64/usr/local/bin/sm .
      - cp config.yaml sm_{{.VERSION}}_amd64/etc/sm/
      - |
        cat <<EOF > sm_{{.VERSION}}_amd64/DEBIAN/control
        Package: v2k-sm
        Version: {{.VERSION}}
        Section: custom
        Priority: optional
        Architecture: amd64
        Maintainer: Ivan Paraskun <ig.paraskun@gmail.com>
        Description: VEPP-2000 Collider platform service management middleware.
        EOF
      - dpkg-deb --build sm_{{.VERSION}}_amd64
      - rm -r sm_{{.VERSION}}_amd64
    generates:
      - sm_{{.VERSION}}_amd64.deb

  build:arm64:
    env:
      GOOS: linux
      GOARCH: arm64
      CGO_ENABLED: 0
    cmds:
      - go build -o sm_{{.VERSION}}_arm64 .
    generates:
      - sm_{{.VERSION}}_arm64

  build:all:
    cmds:
      - task: build:amd64
      - task: build:arm64
      - envsubst '${VERSION}' < util/install.sh > install.sh

  image:
    cmds:
      - docker build -t {{.DOCKER_REGISTRY}}/v2k.sm:latest .

  publish:
    cmds:
      - docker push {{.DOCKER_REGISTRY}}/v2k.sm:latest

  run:
    env:
      ADDR: ":8080"
      CONFIG_PATH: "{{.CONFIG_DIR}}"
      DEPLOY_PATH: "{{.DEPLOY_DIR}}"
    cmds:
      - go run ./rest

