version: "3"

tasks:
  generate:
    cmds:
      - protoc -I{{.SCHEMA_DIR}} --cpp_out=gen v2k/Log.proto
      - protoc -I{{.SCHEMA_DIR}} --cpp_out=gen v2k/beam/AxisSize.proto
      - protoc -I{{.SCHEMA_DIR}} --cpp_out=gen v2k/beam/Current.proto
      - protoc -I{{.SCHEMA_DIR}} --cpp_out=gen v2k/beam/Emittance.proto
      - protoc -I{{.SCHEMA_DIR}} --cpp_out=gen v2k/beam/EnergySpread.proto
