networks:
  v2k:
    external: true

volumes:
  grafana:
  appsmith:

secrets:
  mq:
    external: true
  redpanda:
    external: true
  redpanda-console:
    external: true

services:
  mq:
    image: ghcr.io/blabtm/v2k.mq:latest
    ports:
      - target: 1883
        published: $MQ_MQTT_PORT
        mode: host
      - target: 20041
        published: $MQ_VCAS_PORT
        mode: host
    secrets:
      - source: mq
        target: /etc/mq/config.yaml
    networks:
      - v2k

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.2
    ports:
      - target: 9090 # localhost
        published: 9090
        mode: host
      - target: 9092 # lan
        published: $RP_KAFKA_PORT
        mode: host
      - target: 9080 # schema registry
        published: $SR_PORT
        mode: ingress
      - target: 9644 # admin
        published: 9644
        mode: ingress
    command:
      - redpanda
      - start
      - --kafka-addr local://0.0.0.0:9090,docker://0.0.0.0:9091,lan://0.0.0.0:9092
      - --advertise-kafka-addr local://localhost:9090,docker://kafka:9091,lan://$RP_KAFKA_HOST:$RP_KAFKA_PORT
      - --schema-registry-addr registry://0.0.0.0:9080
      - --rpc-addr docker://0.0.0.0:33145
      - --advertise-rpc-addr docker://kafka:33145
    secrets:
      - source: redpanda
        target: /etc/redpanda/.bootstrap.yaml
    environment:
      RP_BOOTSTRAP_PASSWORD: $RP_PASS
    networks:
      - v2k

  kafka-console:
    image: docker.redpanda.com/redpandadata/console:v3.3.2
    ports:
      - target: 8080
        published: $RP_CONSOLE_PORT
        mode: ingress
    environment:
      CONFIG_FILEPATH: /etc/console/config.yaml
    secrets:
      - source: redpanda-console
        target: /etc/console/config.yaml
    depends_on:
      - kafka
    networks:
      - v2k

  service-manager:
    image: ghcr.io/blabtm/v2k.sm:latest
    ports:
      - target: 80
        published: $SM_PORT
        mode: ingress
    environment:
      CONFIG_PATH: /etc/v2k/config
      DEPLOY_PATH: /etc/v2k/deploy
      DOCS_PATH: /etc/v2k/docs
    volumes:
      - $REPO_PATH/config:/etc/v2k/config
      - $REPO_PATH/.deploy:/etc/v2k/deploy
      - $REPO_PATH/.docs:/etc/v2k/docs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - v2k

  grafana:
    image: ghcr.io/blabtm/v2k.grafana:latest
    ports:
      - target: 3000
        published: $GRAFANA_PORT
        mode: ingress
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hamedkarbasi93-kafka-datasource
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - v2k

  appsmith:
    image: appsmith/appsmith-ee:latest
    ports:
      - target: 80
        published: $APPSMITH_PORT
        mode: ingress
    volumes:
      - appsmith:/appsmith-stacks
    networks:
      - v2k

#  tooljet:
#    image: tooljet/tooljet-ce:ce-lts-latest
#    ports:
#      - target: 80
#        published: $TJ_PORT
#        mode: ingress
#    command: npm run start:prod
#    tty: true
#    stdin_open: true
#    environment:
#      TOOLJET_HOST: http://$TJ_HOST:$TJ_PORT
#      SERVE_CLIENT: "true"
#      PORT: 80
#      LOCKBOX_MASTER_KEY: $TJ_LOCKBOX_MASTER_KEY
#      SECRET_KEY_BASE: $TJ_SECRET_KEY_BASE
#      ORM_LOGGING: all
#      PG_HOST: $DB_HOST
#      PG_PORT: $DB_PORT
#      PG_DB: tooljet
#      PG_USER: $DB_USER
#      PG_PASS: $DB_PASS
#      TOOLJET_DB_HOST: $DB_HOST
#      TOOLJET_DB_PORT: $DB_PORT
#      TOOLJET_DB: tooljet_db
#      TOOLJET_DB_USER: $DB_USER
#      TOOLJET_DB_PASS: $DB_PASS
#      PGRST_HOST: localhost:3002
#      PGRST_DB_URI: postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/tooljet_db
#      PGRST_JWT_SECRET: $TJ_JWT_SECRET
#      PGRST_SERVER_PORT: 3002
#      PGRST_DB_PRE_CONFIG: postgrest.pre_config
#      ENABLE_MULTIPLAYER_EDITING: "true"
#      ENABLE_MARKETPLACE_FEATURE: "true"
#      USER_SESSION_EXPIRY: 2880
#      DEPLOYMENT_PLATFORM: docker
#    networks:
#      - v2k
#    depends_on:
#      - service-manager
#      - grafana
