version: "3"

includes:
  sys:
    taskfile: ./sys/Taskfile.yaml
    dir: ./sys
  grafana:
    taskfile: ./grafana/Taskfile.yaml
    dir: ./grafana
  sm:
    taskfile: ./sm/Taskfile.yaml
    dir: ./sm
  mq:
    taskfile: ./mq/Taskfile.yaml
    dir: ./mq
    optional: true
  connect:
    taskfile: ./connect/Taskfile.yaml
    dir: ./connect

tasks:
  init:
    cmds:
      - cp env/build.env.template env/build.env
      - cp env/secret.env.template env/secret.env
    generates:
      - env/build.env
      - env/secret.env

  deploy:
    deps: [config:setup]
    cmds:
      - task: deploy:mq
      - task: deploy:rp
      - task: deploy:sm
      - task: deploy:gf
      - task: deploy:as

  deploy:db:
    cmds:
      - docker stack deploy -c compose/compose.db.yaml {{.CLI_ARGS}} v2k_db

  deploy:mq:
    cmds:
      - docker stack deploy -c compose/compose.mq.yaml {{.CLI_ARGS}} v2k_mq

  deploy:rp:
    cmds:
      - docker stack deploy -c compose/compose.rp.yaml {{.CLI_ARGS}} v2k_rp

  deploy:sm:
    cmds:
      - mkdir -p ../.deploy
      - docker stack deploy -c compose/compose.sm.yaml {{.CLI_ARGS}} v2k_sm

  deploy:gf:
    cmds:
      - mkdir -p ../.obs.prov
      - docker stack deploy -c compose/compose.gf.yaml {{.CLI_ARGS}} v2k_gf

  deploy:as:
    cmds:
      - docker stack deploy -c compose/compose.as.yaml {{.CLI_ARGS}} v2k_as

  setup:
    cmds:
      - task: setup:rp
      - task: setup:gf

  setup:rp:
    cmds:
      - "{{.TOOLS_DIR}}/setup/setup-redpanda.sh"

  setup:gf:
    cmds:
      - "{{.TOOLS_DIR}}/setup/setup-grafana.sh"

  config:setup:
    cmds:
      - task: config:mq:setup
      - task: config:rp:setup
    internal: true

  config:mq:setup:
    cmds:
      - docker secret rm v2k-mq || true
      - envsubst < config/mq.yaml | docker secret create v2k-mq -
    internal: true

  config:rp:setup:
    cmds:
      - docker secret rm v2k-redpanda || true
      - docker secret rm v2k-redpanda-console || true
      - envsubst < config/redpanda.yaml | docker secret create v2k-redpanda -
      - envsubst < config/redpanda-console.yaml | docker secret create v2k-redpanda-console -
    internal: true

  config:clean:
    cmds:
      - docker secret rm v2k-mq || true
      - docker secret rm v2k-redpanda || true
      - docker secret rm v2k-redpanda-console || true
    internal: true
