version: "3"

includes:
  grafana:
    taskfile: ./grafana/Taskfile.yaml
    dir: ./grafana
  sm:
    taskfile: ./sm/Taskfile.yaml
    dir: ./sm
  mq:
    taskfile: ./mq/Taskfile.yaml
    dir: ./mq
  connect:
    taskfile: ./connect/Taskfile.yaml
    dir: ./connect

tasks:
  sync:
    desc: synchronize service deployments
    dir: ..
    cmds:
      - "{{.TOOLS_DIR}}/sync/sync.sh"

  config:clean:
    desc: remove secrets
    cmds:
      - docker secret rm mq || true
      - docker secret rm redpanda || true
      - docker secret rm redpanda-console || true

  config:install:
    desc: inject secrets and install platform configurations
    cmds:
      - task: config:clean
      - envsubst < config/mq.yaml | docker secret create mq - || true
      - envsubst < config/redpanda.yaml | docker secret create redpanda - || true
      - envsubst < config/redpanda-console.yaml | docker secret create redpanda-console - || true

  network:create:
    desc: create internal docker network
    cmds:
      - docker network create --driver overlay --attachable v2k || true

  deploy:db:
    cmds:
      - docker stack deploy -c compose/compose.db.yaml {{.CLI_ARGS}} v2k_db

  deploy:mq:
    cmds:
      - docker stack deploy -c compose/compose.mq.yaml {{.CLI_ARGS}} v2k_mq

  deploy:rp:
    cmds:
      - docker stack deploy -c compose/compose.rp.yaml {{.CLI_ARGS}} v2k_rp

  deploy:sm:
    cmds:
      - docker stack deploy -c compose/compose.sm.yaml {{.CLI_ARGS}} v2k_sm

  deploy:
    desc: deploy platform to the swarm
    cmds:
      - |
        docker compose                      \
          -f compose/compose.mq.yaml        \
          -f compose/compose.rp.yaml        \
          -f compose/compose.sm.yaml        \
          -f compose/compose.grafana.yaml   \
          -f compose/compose.appsmith.yaml  \
        config | docker stack deploy -c - v2k
