version: "3"

includes:
  hfr_v:
    taskfile: ./hfr_v/Taskfile.yaml
    dir: ./hfr_v
  ccd:
    taskfile: ./ccd/Taskfile.yaml
    dir: ./ccd
  em_es:
    taskfile: ./em_es/Taskfile.yaml
    dir: ./em_es

tasks:
  build:
    cmds:
      - cmake --build build {{.CLI_ARGS}}
