version: "3"

includes:
  hfr-v:
    taskfile: ./hfr-v/Taskfile.yaml
    dir: ./hfr-v
  ccd:
    taskfile: ./ccd/Taskfile.yaml
    dir: ./ccd
  em-es:
    taskfile: ./em-es/Taskfile.yaml
    dir: ./em-es

tasks:
  build:
    cmds:
      - cmake --build build {{.CLI_ARGS}}
