kafka:
  brokers: ["$RP_HOST:$RP_LAN_PORT"]
schemaRegistry:
  enabled: true
  urls: ["http://$RP_HOST:$RP_SR_PORT"]
redpanda:
  adminApi:
    enabled: true
    urls: ["http://rp:9644"]
    authentication:
      basic:
        username: $RP_USER
        password: $RP_PASS
      impersonateUser: false
