networks:
  v2k:
    external: true

services:
  sim:
    image: ghcr.io/blabtm/v2k.em-es.sim:latest
    environment:
      CONFIG_DIR: /etc/v2k
      RP_URI: $RP_KAFKA_HOST:$RP_KAFKA_PORT
      SR_URI: http://$SR_HOST:$SR_PORT
    volumes:
      - /etc/v2k:/etc/v2k
    networks:
      - v2k
