networks:
  v2k:
    external: true

services:
  connect:
    image: docker.redpanda.com/redpandadata/connect
    entrypoint: /bin/sh
    command: -c 'echo "$$CONNECT" > /tmp/connect.yaml && /redpanda-connect -c /tmp/connect.yaml'
    environment:
      CONNECT: |
        input:
          mqtt:
            urls: ["tcp://$MQ_HOST:$MQ_MQTT_PORT"]
            topics: ["$$share/connect/PBUF/#"]
            client_id: "connect-node-$${! uuid_v4() }"

        pipeline:
          processors:
            - mapping: |
                meta topic = meta("mqtt_topic")
                  .trim_prefix("PBUF/")
                  .replace_all("/", ".")
                  .lowercase()

        output:
          kafka_franz:
            seed_brokers: ["$RP_HOST:$RP_LAN_PORT"]
            topic: $${! meta("topic") }

    networks:
      - v2k
    deploy:
      replicas: 1
